[tools]
"tuist" = "4.202.2"
"swiftlint" = "0.65.0"
"swiftformat" = "0.52.10"
"git-cliff" = "2.13.1"

[plugins]
tuist = "https://github.com/asdf-community/asdf-tuist"
swift = "https://github.com/fcrespo82/asdf-swift"
podman = "https://github.com/tvon/asdf-podman.git"
