#!/bin/bash
# mise description="Builds the project using Swift Package Manager in Linux"
set -euo pipefail

CONTAINER_RUNTIME=$(command -v podman || command -v docker)

if [ -z "$CONTAINER_RUNTIME" ]; then
  echo "Neither podman nor docker is available. Please install one to proceed."
  exit 1
fi

$CONTAINER_RUNTIME run --rm \
    --volume "$MISE_PROJECT_ROOT:/package" \
    --workdir "/package" \
    swift:6.0.3 \
    /bin/bash -c \
    "swift build --configuration release --build-path ./.build/linux"
